# Generated by Django 5.2.7 on 2025-11-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Jigme Choden', max_length=100)),
                ('student_id', models.CharField(default='02230283', max_length=20)),
                ('email', models.EmailField(default='jigme@example.com', max_length=254)),
                ('bio', models.TextField(default='Computer Science student passionate about web development and Django framework.')),
                ('interests', models.TextField(default='Web Development, Programming, Technology, Reading')),
                ('skills', models.TextField(default='Python, Django, HTML, CSS, JavaScript, SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Me Information',
            },
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_learned', models.DateField()),
                ('category', models.CharField(choices=[('django', 'Django Framework'), ('python', 'Python Programming'), ('html', 'HTML & CSS'), ('javascript', 'JavaScript'), ('database', 'Database'), ('deployment', 'Deployment')], max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Learning Journey Items',
                'ordering': ['-date_learned'],
            },
        ),
    ]
