# Generated by Django 5.2.7 on 2025-11-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0002_aboutme_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='profile_picture',
        ),
    ]
