# Generated by Django 5.2.7 on 2025-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0003_remove_aboutme_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
