# Generated by Django 5.2.7 on 2025-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0004_aboutme_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin_screenshots/')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Screenshots',
                'ordering': ['display_order'],
            },
        ),
    ]
