# Generated by Django 5.2.7 on 2025-11-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0005_adminscreenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminscreenshots',
            name='description',
        ),
    ]
